/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SPRA;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Andresa M
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtMatAdm = new javax.swing.JTextField();
        labelMatr = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        butLogin = new javax.swing.JButton();
        butRegistrAdm = new javax.swing.JButton();
        labelTitle = new javax.swing.JLabel();
        passwordAdm = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        labelMatr.setBackground(new java.awt.Color(255, 255, 255));
        labelMatr.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        labelMatr.setText("Matrícula ");

        labelSenha.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        labelSenha.setText("Senha");

        butLogin.setText("Login");
        butLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLoginActionPerformed(evt);
            }
        });

        butRegistrAdm.setText("Registrar Administrador");
        butRegistrAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRegistrAdmActionPerformed(evt);
            }
        });

        labelTitle.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        labelTitle.setText("Sistema para Registro de Autorizações - Login");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(labelTitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(butLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelMatr)
                                    .addComponent(labelSenha))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMatAdm, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                    .addComponent(passwordAdm)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(butRegistrAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMatr)
                    .addComponent(txtMatAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSenha)
                    .addComponent(passwordAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(butLogin)
                .addGap(46, 46, 46)
                .addComponent(butRegistrAdm)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butRegistrAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRegistrAdmActionPerformed
        this.setVisible(false);
        CadastroAdministrador in = new CadastroAdministrador();
        in.setVisible(true);
        //sai dessa tela e vai para a de registrar um adiministrador
    }//GEN-LAST:event_butRegistrAdmActionPerformed

    private void butLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLoginActionPerformed
        if ((txtMatAdm.getText().length() != 0) && (passwordAdm.getPassword().length != 0)){
            //condição que verifica se todos os campos estão "ocupados"
            
            Connection conn = null;
            //inicializa a variavel do tipo conexão 
            
            try {
                
                conn = Conexao.getConnection();
                //inicializa a conexão com o banco de dados
                
                Statement stmt = conn.createStatement();
                //cria um statement
                
                stmt.execute("SELECT * "
                             + "FROM administrador "
                             + "WHERE MatAdm like '"+ txtMatAdm.getText()+"' "
                             + "AND Senha like '"+ String.valueOf(passwordAdm.getPassword())+"' ;");
                //comando select do SQL que vai pegar todos os dados do administrador
          
                ResultSet result = stmt.getResultSet();
                //pega os resultados do select
                
                if (result.next()){
                    //verifica se existe um resultado
                    this.setVisible(false);
                    PesquisaAluno in = new PesquisaAluno();
                    User u = new User(result.getString("MatAdm"), result.getString("NomeAdm"), 
                                      result.getString("email"));
                    //cria a variavel do tipo usuario que vai levar os dados para a proxima tela
                    in.setUs(u);
                    in.atualizarMenu();
                    //chama um metodo que vai mudar o campo
                    in.setVisible(true);
                    //abre a proxima tela
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Senha/Matricula errado!", "Mensagem", 
                                          JOptionPane.INFORMATION_MESSAGE);
                    //envia a mensagem de erro se a matricula ou senha estiverem erradas ou não existem
                }
                stmt.close();
                conn.close();
                //fecha a conexão
            } catch(Exception e) {
                e.printStackTrace();
                //trata erros e exceções
            }
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!", "Mensagem", 
                                          JOptionPane.INFORMATION_MESSAGE);
            //da erro se os campos não estiverem preenchidos
        }
    }//GEN-LAST:event_butLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butLogin;
    private javax.swing.JButton butRegistrAdm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelMatr;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPasswordField passwordAdm;
    private javax.swing.JTextField txtMatAdm;
    // End of variables declaration//GEN-END:variables
}
