/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SPRA;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author cliente
 */
public class RegistroAutorizacao extends javax.swing.JFrame {

    /**
     * Creates new form Autorizacao
     */
    public RegistroAutorizacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelMotivo = new javax.swing.JLabel();
        labelMatrAl = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        txtMatAl = new javax.swing.JTextField();
        txtDataAut = new javax.swing.JTextField();
        txtHoraAut = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMotAut = new javax.swing.JTextArea();
        buttRegisAuto = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        labelTitle.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        labelTitle.setText("Sistema para Registro de Autorizações - Autorizações");

        labelMotivo.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        labelMotivo.setText("Motivo");

        labelMatrAl.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        labelMatrAl.setText("Matrícula do Aluno");

        labelData.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        labelData.setText("Data");

        labelHora.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        labelHora.setText("Hora");

        txtMatAl.setEditable(false);

        txtDataAut.setText("formato da data: aaaa-mm-dd");
        txtDataAut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDataAutMouseClicked(evt);
            }
        });
        txtDataAut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataAutActionPerformed(evt);
            }
        });
        txtDataAut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDataAutKeyPressed(evt);
            }
        });

        txtHoraAut.setText("formato da hora: hh:mm");
        txtHoraAut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHoraAutMouseClicked(evt);
            }
        });
        txtHoraAut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHoraAutKeyPressed(evt);
            }
        });

        txtMotAut.setColumns(20);
        txtMotAut.setRows(5);
        txtMotAut.setText("Máximo 200 caracteres");
        txtMotAut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMotAutMouseClicked(evt);
            }
        });
        txtMotAut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMotAutKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMotAutKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMotAutKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtMotAut);

        buttRegisAuto.setText("Finalizar");
        buttRegisAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttRegisAutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitle)
                .addGap(104, 104, 104))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMatrAl)
                            .addComponent(labelData)
                            .addComponent(labelHora)
                            .addComponent(labelMotivo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMatAl, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                .addComponent(txtDataAut)
                                .addComponent(txtHoraAut))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(buttRegisAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMatrAl)
                    .addComponent(txtMatAl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelData)
                    .addComponent(txtDataAut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHora)
                    .addComponent(txtHoraAut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelMotivo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(buttRegisAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    User us;

    public User getUs() {
        return us;
    }

    public void setUs(User us) {
        this.us = us;
    }

    Alun as;

    public Alun getAs() {
        return as;
    }

    public void setAs(Alun as) {
        this.as = as;
    }

    public void alterarAlu() {
        txtMatAl.setText(as.getMatr());
    }


    private void txtDataAutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataAutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataAutActionPerformed

    private void buttRegisAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttRegisAutoActionPerformed
        // TODO add your handling code here:
        if ((txtMatAl.getText().length() != 0) && (txtDataAut.getText().length() != 0)
                && (txtHoraAut.getText().length() != 0) && (txtMotAut.getText().length() != 0)) {

            if (txtMotAut.getText().length() >= 200) {
                JOptionPane.showMessageDialog(null, "Área motivo tem mais de 200 caracteres",
                        "Mensagem", JOptionPane.INFORMATION_MESSAGE);
            } else {

                Connection conn = null;

                try {
                    conn = Conexao.getConnection();
                    Statement stmt = conn.createStatement();

                    String sel = "select MAX(CodAut) as CodAut from autorizacao;";
                    stmt.execute(sel);

                    ResultSet result = stmt.getResultSet();

                    if (result.next()) {
                        
                        String cmd = null;
                        
                        if (String.valueOf(result.getInt("CodAut")) == null) {
                            cmd = "insert into autorizacao values("
                                    + 0 + " ,'" + txtMotAut.getText() + "','"
                                    + txtHoraAut.getText() + "','" + txtDataAut.getText() + "'," + "'"
                                    + us.getMatricula() + "','" + txtMatAl.getText() + "')";   
                        } else {
                            cmd = "insert into autorizacao values("
                                    + (result.getInt("CodAut") + 1) + " ,'" + txtMotAut.getText() + "','"
                                    + txtHoraAut.getText() + "','" + txtDataAut.getText() + "'," + "'"
                                    + us.getMatricula() + "','" + txtMatAl.getText() + "')";
                            
                        }
                        int i = stmt.executeUpdate(cmd);

                        if (i == 0) {
                            JOptionPane.showMessageDialog(null, "ERRO! Registro não inserido.", "Mensagem",
                                    JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(null, "SUCESSO! Autorização cadastrada.", "Mensagem",
                                    JOptionPane.INFORMATION_MESSAGE);
                            this.setVisible(false);

                        }

                    } else {
                        System.out.println("Não existe registro algum.");
                    }
                    stmt.close();
                    conn.close();

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_buttRegisAutoActionPerformed

    private void txtDataAutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDataAutMouseClicked
        txtDataAut.setText("");
    }//GEN-LAST:event_txtDataAutMouseClicked

    private void txtHoraAutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoraAutKeyPressed

    }//GEN-LAST:event_txtHoraAutKeyPressed

    private void txtHoraAutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHoraAutMouseClicked
        txtHoraAut.setText("");
    }//GEN-LAST:event_txtHoraAutMouseClicked

    private void txtMotAutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMotAutMouseClicked
        txtMotAut.setText("");
    }//GEN-LAST:event_txtMotAutMouseClicked

    private void txtDataAutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataAutKeyPressed

    }//GEN-LAST:event_txtDataAutKeyPressed

    private void txtMotAutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMotAutKeyReleased
    }//GEN-LAST:event_txtMotAutKeyReleased

    private void txtMotAutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMotAutKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtMotAutKeyPressed

    private void txtMotAutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMotAutKeyTyped
        // TODO add your handling code here:
        if (txtMotAut.getText().length() >= 198) {
            String expli = txtMotAut.getText();
            txtMotAut.setText(expli);
            JOptionPane.showMessageDialog(null, "Máximo 200 caracteres", "Mensagem",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtMotAutKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroAutorizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroAutorizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroAutorizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroAutorizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroAutorizacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttRegisAuto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel labelMatrAl;
    private javax.swing.JLabel labelMotivo;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JTextField txtDataAut;
    private javax.swing.JTextField txtHoraAut;
    private javax.swing.JTextField txtMatAl;
    private javax.swing.JTextArea txtMotAut;
    // End of variables declaration//GEN-END:variables
}
